# -*- coding: utf-8 -*-
"""DetailedSatelliteImageCyc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l4mOJe3Zwx1y8wnoO8awSqC4Jj5cjyyB
"""

from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import requests
from io import BytesIO

from skimage.feature import graycomatrix, graycoprops
from skimage.filters import sobel, laplace

def load_image(url):
    response = requests.get(url, timeout=10, headers={"User-Agent": "Mozilla/5.0"})
    img = Image.open(BytesIO(response.content)).convert('L')
    return np.array(img)


url = "https://raw.githubusercontent.com/devangiwaghela/SatelliteImageProcessingCycprocess/main/Code/pictures/cyclonemay2019.png"
img = load_image(url)


# GLCM - texture analysis)

def glcm_features(img):
    img_scaled = (img / 8).astype(np.uint8)

    glcm = graycomatrix(
        img_scaled,
        distances=[1, 2],
        angles=[0, np.pi/4],
        levels=32,
        symmetric=True,
        normed=True
    )

    return {
        "contrast": graycoprops(glcm, 'contrast').mean(),
        "energy": graycoprops(glcm, 'energy').mean(),
        "homogeneity": graycoprops(glcm, 'homogeneity').mean()
    }




# CYCLONE CENTER - mass-based estimate)

def cyclone_center(img):
    y, x = np.indices(img.shape)
    total = img.sum() + 1e-6

    cx = (x * img).sum() / total
    cy = (y * img).sum() / total

    return int(cx), int(cy)




# SEVERITY MODEL

def severity_score(glcm, edge_mean, lap_mean):
    score = (
        glcm["contrast"] * 35 +
        glcm["energy"] * 20 +
        edge_mean * 25 +
        lap_mean * 20
    )
    return min(100, max(0, score * 100))

def interpret(score):
    if score > 70:
        return "🌪️ Severe Cyclone (Strong spiral + high organization)"
    elif score > 40:
        return "🌪️ Moderate Cyclone (Developing system)"
    else:
        return "🌤️ Weak Disturbance (Low structure)"




# FEATURE EXTRACTION

glcm = glcm_features(img)

sobel_img = sobel(img)
lap = laplace(img)

edge_mean = np.mean(sobel_img)
lap_mean = np.mean(np.abs(lap))

cx, cy = cyclone_center(img)
score = severity_score(glcm, edge_mean, lap_mean)





# ENHANCED LAPLACIAN

lap_abs = np.abs(lap)
lap_norm = (lap_abs - lap_abs.min()) / (lap_abs.max() - lap_abs.min() + 1e-6)

spiral_mask = sobel_img > np.percentile(sobel_img, 85)




# OUTPUT REPORT

print("\n🌪️ CYCLONE INTELLIGENCE SYSTEM REPORT\n")

print("📊 FEATURES:")
print(f"Contrast     : {glcm['contrast']:.4f}")
print(f"Energy       : {glcm['energy']:.4f}")
print(f"Homogeneity  : {glcm['homogeneity']:.4f}")
print(f"Edge Mean    : {edge_mean:.4f}")
print(f"Laplacian    : {lap_mean:.4f}")

print("\n📍 ESTIMATED CYCLONE CENTER:")
print(f"X: {cx}, Y: {cy}")

print("\n⚡ SEVERITY SCORE:")
print(f"{score:.2f} / 100")

print("\n🧭 INTERPRETATION:")
print(interpret(score))




# VISUALIZATION (RESEARCH STYLE)
plt.figure(figsize=(12,10))

# Original image
plt.subplot(2,2,1)
plt.imshow(img, cmap='gray')
plt.title("Satellite Image")
plt.xlabel("X-axis (pixels)")
plt.ylabel("Y-axis (pixels)")

# Sobel edges
plt.subplot(2,2,2)
plt.imshow(sobel_img, cmap='gray')
plt.title("Sobel Edge Map (Structure)")
plt.xlabel("X-axis")
plt.ylabel("Y-axis")

# Laplacian heatmap (FIXED)
plt.subplot(2,2,3)
plt.imshow(lap_norm, cmap='inferno')
plt.title("Laplacian Energy Map")
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.colorbar(label="Energy")

# Spiral highlight overlay
plt.subplot(2,2,4)
plt.imshow(img, cmap='gray')
plt.contour(spiral_mask, colors='red', linewidths=0.5)
plt.title("Detected High-Structure Regions (Spiral Proxy)")
plt.xlabel("X-axis")
plt.ylabel("Y-axis")

plt.tight_layout()
plt.show()
