# -*- coding: utf-8 -*-
"""SimpleCycloneAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v_voonwxLkTauNrPAAF5X5p8g8n1rRd1
"""

from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import requests
from io import BytesIO

# ✅ Correct RAW GitHub URL
url = "https://raw.githubusercontent.com/devangiwaghela/SatelliteImageProcessingCycprocess/main/Code/pictures/cyclonemay2019.png"

response = requests.get(url, timeout=10)
response.raise_for_status()

img = Image.open(BytesIO(response.content)).convert('L')

img_array = np.array(img)
brightened = np.clip(img_array + 40, 0, 255)

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.imshow(img_array, cmap='gray')
plt.title('Original Image')
plt.axis('off')

plt.subplot(1,2,2)
plt.imshow(brightened, cmap='gray')
plt.title('Brightness Increased')
plt.axis('off')

plt.show()

